
@RaffleApi_HostAddress = http://localhost:5041

### Create a raffle
# @name createRaffle
POST {{RaffleApi_HostAddress}}/raffles
Content-Type: application/json

{
  "title": "The Great Raffle",
  "numberOfTickets": 1000,
  "price": 500
}
### Get the raffle by ID
@location = {{createRaffle.response.headers.Location}}

###
GET {{RaffleApi_HostAddress}}{{location}}
Accept: application/json
